require "rake"

ref_name = "../data/cropped/IITmean_t1.nii_cropped.nii.gz"
ref_mask = "../data/cropped/IITmean_t1.nii_cropped_mask.nii.gz"
atlas_name = "../data/cropped/IIT_GM_Desikan_atlas.nii_cropped.nii.gz"
files = Rake::FileList["../data/cropped/t*_cropped.nii.gz"]
warped_atlases = []

namespace :fsl do

  for file in files

    basename = File.basename(file, ".nii.gz")
    output_dir = "../data/fsl/#{basename}"
    directory output_dir

    omat = "#{output_dir}/#{basename}.mat"
    desc "flirt file #{basename}"
    file omat => [file, output_dir] do |t|
      sh "/usr/share/fsl/5.0/bin/flirt " <<
      "-in #{ref_name} -ref #{t.source} " <<
      "-omat #{t.name} " <<
      "-bins 256 -cost mutualinfo " <<
      "-searchrx 0 0 -searchry 0 0 -searchrz 0 0 " <<
      "-dof 12 -interp trilinear "
    end

    mask = file.gsub("_cropped", "_cropped_mask")
    warp_field = "#{output_dir}/#{basename}_warp_field.nii.gz"
    desc "fnirt warp field #{basename}"
    file warp_field => [omat, file, mask, output_dir] do |t|
      sh "/usr/share/fsl/5.0/bin/fnirt " <<
      "--in=#{ref_name} --ref=#{t.prerequisites[1]} " <<
      "--aff=#{t.source} " <<
      "--fout=#{t.name} " <<
      "--inmask=#{ref_mask} " <<
      "--refmask=#{t.prerequisites[2]} " <<
      "--warpres=10,10,10 " <<
      "--subsamp=8,4,2,1 " <<
      "--reffwhm=2,0,0,0 " <<
      "--lambda=300,100,50,25 " <<
      "--intmod=global_linear"
    end

    warped_atlas = "#{output_dir}/#{basename}_warped_atlas.nii.gz"
    desc "apply warp field to atlas #{basename}"
    file warped_atlas => [warp_field, file, output_dir] do |t|
      sh "/usr/lib/fsl/5.0/applywarp " <<
      "--ref=#{t.prerequisites[1]} --in=#{atlas_name} --warp=#{t.source} " <<
      "--out=#{t.name} --interp=nn"
    end
    warped_atlases.push warped_atlas

  end

  desc "warp all images"
  multitask :all => warped_atlases

end

namespace :spom do

  region_names = []
  for warped_atlas in warped_atlases

    region_name = warped_atlas.gsub("_warped_atlas.nii.gz", "_left_thalamus.nrrd")
    region_names.push region_name
    desc "split atlas into regions #{region_name}"
    file region_name => [warped_atlas, "split_regions.py"] do |t|
      sh "python #{t.prerequisites[1]} #{t.source}"
    end

  end

  desc "split all atlases"
  multitask :split_atlases => region_names

  desikan_label_ids = {
      "left_thalamus" => 10,
      "right_thalamus" => 49,
      "left_caudate" => 11,
      "right_caudate" => 50,
      "left_putamen" => 12,
      "right_putamen" => 51,
      "left_pallidum" => 13,
      "right_pallidum" => 52,
      "left_hippocampus" => 17,
      "right_hippocampus" => 53,
      "left_amygdala" => 18,
      "right_amygdala" => 54,
  }

  for region_name in desikan_label_ids.keys
    folder = "../data/lists/#{region_name}"
    directory folder

    desc region_name
    task region_name => folder do |t|
      Dir.chdir(t.source) do
        p region_name
        sh "~/src/SPoM/sumOfTwoPoisson/mainSumOfTwoPoissonShapeAnalysis list1.txt list0.txt mean_image.nii mean_vtp.vtp"
      end
    end
  end

  desc "all poisson analyses"
  task :all => desikan_label_ids.keys

end
